// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDW-J6ycZrxk8wbGOi7xIDnxkMoO4QsfXQ',
    appId: '1:475249759344:android:e1b4a202d67b8c65fbd0b5',
    messagingSenderId: '475249759344',
    projectId: 'men-matter-too-space',
    databaseURL: 'https://men-matter-too-space-default-rtdb.firebaseio.com',
    storageBucket: 'men-matter-too-space.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtw_AOlT2zWX8rqbWaS1rjCNANt_ewvlU',
    appId: '1:475249759344:ios:0674930559ec3f12fbd0b5',
    messagingSenderId: '475249759344',
    projectId: 'men-matter-too-space',
    databaseURL: 'https://men-matter-too-space-default-rtdb.firebaseio.com',
    storageBucket: 'men-matter-too-space.firebasestorage.app',
    iosClientId: '475249759344-9bvd1cfbl4m9na5vifrs7757phio59it.apps.googleusercontent.com',
    iosBundleId: 'com.adityatripathi.cookd',
  );
}
