final data = [
  {
    "name": "Homemade Chicken Soup",
    "desc":
        "A comforting bowl of homemade chicken broth with vegetables and noodles.",
    "rating": 4.9,
    "prep_time": "40 min",
    "energy": 300,
    "ingredients": [
      "Chicken",
      "Carrots",
      "Celery",
      "Onion",
      "Noodles",
      "Garlic",
    ],
    "allergy": ["Gluten (if using noodles)"],
    "macros": {"protein": 30, "carbs": 35, "fat": 10},
    "hashtags": ["#comfortfood", "#chickensoup", "#homemade", "#healthy"],
    "spots": 3,
    "location": "Logan Hall LTB",
    "time": "5m ago",
  },
  {
    "name": "Mom's Meatloaf",
    "desc": "A classic meatloaf with a rich tomato glaze, just like home.",
    "rating": 4.8,
    "prep_time": "50 min",
    "energy": 450,
    "ingredients": [
      "Ground beef",
      "Bread crumbs",
      "Eggs",
      "Onion",
      "Tomato sauce",
    ],
    "allergy": ["Gluten", "Eggs"],
    "macros": {"protein": 40, "carbs": 30, "fat": 22},
    "hashtags": ["#classicrecipe", "#meatloaf", "#dinner", "#familydinner"],
    "spots": 7,
    "location": "Woodside Building",
    "time": "20m ago",
  },
  {
    "name": "Grandma's Apple Pie",
    "desc": "Sweet and spiced apple filling in a flaky homemade crust.",
    "rating": 4.9,
    "prep_time": "60 min",
    "energy": 500,
    "ingredients": ["Apples", "Flour", "Butter", "Cinnamon", "Sugar"],
    "allergy": ["Gluten", "Dairy"],
    "macros": {"protein": 5, "carbs": 75, "fat": 18},
    "hashtags": ["#dessert", "#applepie", "#homemade", "#baking"],
    "spots": 2,
    "location": "Lemon",
    "time": "15m ago",
  },
  {
    "name": "Slow-Cooked Beef Stew",
    "desc":
        "Tender beef chunks simmered with potatoes and carrots in a savory broth.",
    "rating": 4.9,
    "prep_time": "4 hours",
    "energy": 550,
    "ingredients": [
      "Beef",
      "Potatoes",
      "Carrots",
      "Onion",
      "Garlic",
      "Beef broth",
    ],
    "allergy": [],
    "macros": {"protein": 45, "carbs": 40, "fat": 20},
    "hashtags": ["#slowcooker", "#beefstew", "#winterfood", "#hearty"],
    "spots": 8,
    "location": "Scented Lawn",
    "time": "45m ago",
  },
  {
    "name": "Baked Mac & Cheese",
    "desc": "Cheesy, creamy, and baked to golden perfection.",
    "rating": 4.7,
    "prep_time": "35 min",
    "energy": 650,
    "ingredients": ["Macaroni", "Cheddar cheese", "Milk", "Butter", "Flour"],
    "allergy": ["Dairy", "Gluten"],
    "macros": {"protein": 25, "carbs": 70, "fat": 30},
    "hashtags": ["#comfortfood", "#macandcheese", "#cheesy", "#familyfavorite"],
    "spots": 4,
    "location": "Logan Hall LTB",
    "time": "30m ago",
  },
  {
    "name": "Stuffed Bell Peppers",
    "desc":
        "Bell peppers filled with a hearty mix of rice, beef, and tomatoes.",
    "rating": 4.6,
    "prep_time": "45 min",
    "energy": 400,
    "ingredients": [
      "Bell peppers",
      "Ground beef",
      "Rice",
      "Tomato sauce",
      "Garlic",
    ],
    "allergy": [],
    "macros": {"protein": 30, "carbs": 50, "fat": 10},
    "hashtags": [
      "#healthydinner",
      "#stuffedpeppers",
      "#lowfat",
      "#highprotein",
    ],
    "spots": 9,
    "location": "Woodside Building",
    "time": "10m ago",
  },
  {
    "name": "Homestyle Pancakes",
    "desc": "Fluffy homemade pancakes served with maple syrup.",
    "rating": 4.8,
    "prep_time": "20 min",
    "energy": 500,
    "ingredients": ["Flour", "Milk", "Eggs", "Sugar", "Baking powder"],
    "allergy": ["Gluten", "Dairy", "Eggs"],
    "macros": {"protein": 12, "carbs": 80, "fat": 18},
    "hashtags": ["#breakfast", "#pancakes", "#homemade", "#maplesyrup"],
    "spots": 3,
    "location": "Scented Lawn",
    "time": "25m ago",
  },
  {
    "name": "Classic Mashed Potatoes",
    "desc": "Creamy mashed potatoes with butter and cream.",
    "rating": 4.7,
    "prep_time": "25 min",
    "energy": 350,
    "ingredients": ["Potatoes", "Butter", "Milk", "Salt", "Pepper"],
    "allergy": ["Dairy"],
    "macros": {"protein": 5, "carbs": 50, "fat": 15},
    "hashtags": ["#sidedish", "#mashedpotatoes", "#classic", "#comfortfood"],
    "spots": 1,
    "location": "Lemon",
    "time": "50m ago",
  },
  {
    "name": "Sunday Roast Chicken",
    "desc": "Juicy roast chicken with garlic herb butter.",
    "rating": 4.9,
    "prep_time": "90 min",
    "energy": 600,
    "ingredients": ["Whole chicken", "Garlic", "Butter", "Thyme", "Lemon"],
    "allergy": ["Dairy"],
    "macros": {"protein": 50, "carbs": 5, "fat": 40},
    "hashtags": ["#sundayroast", "#roastchicken", "#familydinner", "#classic"],
    "spots": 6,
    "location": "Logan Hall LTB",
    "time": "40m ago",
  },
  {
    "name": "Hearty Vegetable Soup",
    "desc": "A warm and nourishing soup packed with fresh vegetables.",
    "rating": 4.8,
    "prep_time": "40 min",
    "energy": 250,
    "ingredients": [
      "Carrots",
      "Celery",
      "Tomatoes",
      "Potatoes",
      "Vegetable broth",
    ],
    "allergy": [],
    "macros": {"protein": 8, "carbs": 45, "fat": 5},
    "hashtags": ["#vegetarian", "#veggiesoup", "#healthy", "#lowcalorie"],
    "spots": 5,
    "location": "Woodside Building",
    "time": "35m ago",
  },
  {
    "name": "Creamy Alfredo Pasta",
    "desc": "Rich and creamy Alfredo sauce tossed with fettuccine pasta.",
    "rating": 4.7,
    "prep_time": "25 min",
    "energy": 700,
    "ingredients": [
      "Fettuccine",
      "Heavy cream",
      "Parmesan cheese",
      "Butter",
      "Garlic",
    ],
    "allergy": ["Dairy", "Gluten"],
    "macros": {"protein": 20, "carbs": 80, "fat": 30},
    "hashtags": ["#pasta", "#alfredo", "#creamy", "#italianfood"],
    "spots": 2,
    "location": "Scented Lawn",
    "time": "15m ago",
  },
  {
    "name": "Homemade Chicken Curry",
    "desc":
        "Tender chicken cooked in a flavorful curry sauce with aromatic spices.",
    "rating": 4.9,
    "prep_time": "45 min",
    "energy": 550,
    "ingredients": [
      "Chicken",
      "Onion",
      "Garlic",
      "Ginger",
      "Tomatoes",
      "Curry powder",
      "Coconut milk",
    ],
    "allergy": ["Coconut (if using coconut milk)"],
    "macros": {"protein": 40, "carbs": 30, "fat": 20},
    "hashtags": ["#curry", "#chickencurry", "#spicy", "#homemade"],
    "spots": 10,
    "location": "Lemon",
    "time": "5m ago",
  },
];
